services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    image: migrate/migrate:latest
    command:
      - "-path=/migrations"
      - "-database=postgres://postgres:postgres@postgres:5432/appdb?sslmode=disable"
      - "up"
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy

  app-http:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: [ "http" ]
    ports:
      - "8080:8080"

    environment:
      DB__DSN: postgres://postgres:postgres@postgres:5432/appdb?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    profiles: [ app ]

  app-grpc:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: [ "grpc" ]
    ports:
      - "50051:50051"

    environment:
      DB__DSN: postgres://postgres:postgres@postgres:5432/appdb?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    profiles: [ app ]

  app-consumer:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: [ "consumer" ]

    environment:
      DB__DSN: postgres://postgres:postgres@postgres:5432/appdb?sslmode=disable
      CONSUMER__BROKERS: kafka:9092
    depends_on:
      postgres:
        condition: service_healthy
    profiles: [ app ]

  kafka:
    image: apache/kafka:latest
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: template-kafka-cluster-id-01
    ports:
      - "9094:9092"
    profiles: [ kafka ]

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otelcol/config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otelcol/config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP
    profiles: [ observability ]

volumes:
  postgres_data: