// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/nawafswe/go-service-starter-kit/internal/httpx (interfaces: Doer)

package mock

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

type MockDoer struct {
	ctrl     *gomock.Controller
	recorder *MockDoerMockRecorder
}

type MockDoerMockRecorder struct {
	mock *MockDoer
}

func NewMockDoer(ctrl *gomock.Controller) *MockDoer {
	mock := &MockDoer{ctrl: ctrl}
	mock.recorder = &MockDoerMockRecorder{mock}
	return mock
}

func (m *MockDoer) EXPECT() *MockDoerMockRecorder {
	return m.recorder
}

func (m *MockDoer) Do(req *http.Request) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Do", req)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (mr *MockDoerMockRecorder) Do(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Do", reflect.TypeOf((*MockDoer)(nil).Do), req)
}
